In [62]:
import pandas as pd
import numpy as np
import warnings; warnings.filterwarnings('ignore')

movies=pd.read_csv('./data/tmdb_5000_movies.csv')
print(movies.shape)
movies.head(1)

(4803, 20)


budget  \
0  237000000   

                                                                                                                                   genres  \
0  [{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]   

                      homepage     id  \
0  http://www.avatarmovie.com/  19995   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              keywords  \
0  [{"id": 1463, "name": "culture clash"}, {"id": 2964, "name": "future"}, {"id": 3386, "name": "space war"}, {"id": 3388, "name": "space colony"}, {"id": 3679, "name": "society"}, {"id": 3801, "name": "space travel"}, {"id": 9685, "name": "futuristic"}, {"id": 9840, "name": "romance"}, {"id": 9882, "name": "space"}, {"id": 9951, "name": "alien"}, {"id": 10148, "name": "tribe"}, {"id": 10158, "name": "alien planet"}, {"id": 10987, "name": "cgi"}, {"id": 11399, "name": "marine"}, {"id": 13065, "...   

  original_language original_title  \
0                en         Avatar   

                                                                                                                                                                          overview  \
0  In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.   

   popularity  \
0  150.437577   

                                                                                                                                                                                          production_companies  \
0  [{"name": "Ingenious Film Partners", "id": 289}, {"name": "Twentieth Century Fox Film Corporation", "id": 306}, {"name": "Dune Entertainment", "id": 444}, {"name": "Lightstorm Entertainment", "id": 574}]   

                                                                                         production_countries  \
0  [{"iso_3166_1": "US", "name": "United States of America"}, {"iso_3166_1": "GB", "name": "United Kingdom"}]   

  release_date     revenue  runtime  \
0   2009-12-10  2787965087    162.0   

                                                                        spoken_languages  \
0  [{"iso_639_1": "en", "name": "English"}, {"iso_639_1": "es", "name": "Espa\u00f1ol"}]   

     status                      tagline   title  vote_average  vote_count  
0  Released  Enter the World of Pandora.  Avatar           7.2       11800

In [63]:
movies_df = movies[['id', 'title', 'genres', 'vote_average', 'vote_count',
                   'popularity', 'keywords', 'overview']]

In [64]:
pd.set_option('max_colwidth', 500)
movies_df[['genres', 'keywords']][:1]

genres  \
0  [{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              keywords  
0  [{"id": 1463, "name": "culture clash"}, {"id": 2964, "name": "future"}, {"id": 3386, "name": "space war"}, {"id": 3388, "name": "space colony"}, {"id": 3679, "name": "society"}, {"id": 3801, "name": "space travel"}, {"id": 9685, "name": "futuristic"}, {"id": 9840, "name": "romance"}, {"id": 9882, "name": "space"}, {"id": 9951, "name": "alien"}, {"id": 10148, "name": "tribe"}, {"id": 10158, "name": "alien planet"}, {"id": 10987, "name": "cgi"}, {"id": 11399, "name": "marine"}, {"id": 13065, "...

In [65]:
movies_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   id            4803 non-null   int64  
 1   title         4803 non-null   object 
 2   genres        4803 non-null   object 
 3   vote_average  4803 non-null   float64
 4   vote_count    4803 non-null   int64  
 5   popularity    4803 non-null   float64
 6   keywords      4803 non-null   object 
 7   overview      4800 non-null   object 
dtypes: float64(2), int64(2), object(4)
memory usage: 300.3+ KB


In [66]:
#결과값 : [action, adventure...]
from ast import literal_eval #리터럴 이발 : "1+2"하면 그대로가 아니라 3이 나옴. 문자를 가공해서 객체로 만들어줌. 파싱함.

movies_df['genres'] = movies_df['genres'].apply(literal_eval) #함수를 태우면 파싱해서.
movies_df['keywords'] = movies_df['keywords'].apply(literal_eval)

In [67]:
movies_df['genres'].head(1)

0    [{'id': 28, 'name': 'Action'}, {'id': 12, 'name': 'Adventure'}, {'id': 14, 'name': 'Fantasy'}, {'id': 878, 'name': 'Science Fiction'}]
Name: genres, dtype: object

In [68]:

movies_df['genres'] = movies_df['genres'].apply(lambda x : [y['name'] for y in x]) #만들어서 자기자신에 넣어라
movies_df['keywords'] = movies_df['keywords'].apply(lambda x : [y['name'] for y in x])
movies_df[['genres', 'keywords']][:1]

genres  \
0  [Action, Adventure, Fantasy, Science Fiction]   

                                                                                                                                                                                                                   keywords  
0  [culture clash, future, space war, space colony, society, space travel, futuristic, romance, space, alien, tribe, alien planet, cgi, marine, soldier, battle, love affair, anti war, power relations, mind and soul, 3d]

In [69]:
movies_df['genres']

0       [Action, Adventure, Fantasy, Science Fiction]
1                        [Adventure, Fantasy, Action]
2                          [Action, Adventure, Crime]
3                    [Action, Crime, Drama, Thriller]
4                [Action, Adventure, Science Fiction]
                            ...                      
4798                        [Action, Crime, Thriller]
4799                                [Comedy, Romance]
4800               [Comedy, Drama, Romance, TV Movie]
4801                                               []
4802                                    [Documentary]
Name: genres, Length: 4803, dtype: object

## 장르 콘텐츠 필터링을 이용한 영화 추천 

### 장르 문자열을 벡터화(Count 기반)

In [70]:
# test : join
a = ('*').join(['test', 'test2'])
type(a)

str

In [71]:
# test : ngram_range
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
corpus = [
    'This is the first document.',
    'This document is the second document.',
    'And this is the third one.',
    'Is this the first document?',
]
vectorizer2 = CountVectorizer(analyzer='word', ngram_range=(1, 3))
X2 = vectorizer2.fit_transform(corpus)
vectorizer2.get_feature_names_out()
## 결과 출력
print(vectorizer2.get_feature_names_out())
pd.DataFrame(X2.toarray(), columns=list(vectorizer2.get_feature_names_out()))

# 단어 하나마다 토큰화함

['and' 'and this' 'and this is' 'document' 'document is' 'document is the'
 'first' 'first document' 'is' 'is the' 'is the first' 'is the second'
 'is the third' 'is this' 'is this the' 'one' 'second' 'second document'
 'the' 'the first' 'the first document' 'the second' 'the second document'
 'the third' 'the third one' 'third' 'third one' 'this' 'this document'
 'this document is' 'this is' 'this is the' 'this the' 'this the first']


and  and this  and this is  document  document is  document is the  first  \
0    0         0            0         1            0                0      1   
1    0         0            0         2            1                1      0   
2    1         1            1         0            0                0      0   
3    0         0            0         1            0                0      1   

   first document  is  is the  ...  the third one  third  third one  this  \
0               1   1       1  ...              0      0          0     1   
1               0   1       1  ...              0      0          0     1   
2               0   1       1  ...              1      1          1     1   
3               1   1       0  ...              0      0          0     1   

   this document  this document is  this is  this is the  this the  \
0              0                 0        1            1         0   
1              1                 1        0            0         0   
2              0                 0        1            1         0   
3              0                 0        0            0         1   

   this the first  
0               0  
1               0  
2               0  
3               1  

[4 rows x 34 columns]

In [72]:
from sklearn.feature_extraction.text import CountVectorizer

# min_df : 전체문서에서 너무 낮은 빈도수를 가지는 단어일 경우 제외
# max_df : 전체문서에서 너무 높은 빈도수를 가지는 단어일 경우 제외

count_vect = CountVectorizer(min_df=0, ngram_range=(1,2))
movies_df['genres_literal'] = movies_df['genres'].apply(lambda x : (' ').join(x))
genre_mat = count_vect.fit_transform(movies_df['genres_literal'])
print(genre_mat.shape)

(4803, 276)


In [73]:
pd.DataFrame(genre_mat.toarray(), columns=list(count_vect.get_feature_names_out()))

action  action adventure  action animation  action comedy  action crime  \
0          1                 1                 0              0             0   
1          1                 0                 0              0             0   
2          1                 1                 0              0             0   
3          1                 0                 0              0             1   
4          1                 1                 0              0             0   
...      ...               ...               ...            ...           ...   
4798       1                 0                 0              0             1   
4799       0                 0                 0              0             0   
4800       0                 0                 0              0             0   
4801       0                 0                 0              0             0   
4802       0                 0                 0              0             0   

      action drama  action family  action fantasy  action history  \
0                0              0               0               0   
1                0              0               0               0   
2                0              0               0               0   
3                0              0               0               0   
4                0              0               0               0   
...            ...            ...             ...             ...   
4798             0              0               0               0   
4799             0              0               0               0   
4800             0              0               0               0   
4801             0              0               0               0   
4802             0              0               0               0   

      action horror  ...  western action  western adventure  \
0                 0  ...               0                  0   
1                 0  ...               0                  0   
2                 0  ...               0                  0   
3                 0  ...               0                  0   
4                 0  ...               0                  0   
...             ...  ...             ...                ...   
4798              0  ...               0                  0   
4799              0  ...               0                  0   
4800              0  ...               0                  0   
4801              0  ...               0                  0   
4802              0  ...               0                  0   

      western animation  western comedy  western crime  western drama  \
0                     0               0              0              0   
1                     0               0              0              0   
2                     0               0              0              0   
3                     0               0              0              0   
4                     0               0              0              0   
...                 ...             ...            ...            ...   
4798                  0               0              0              0   
4799                  0               0              0              0   
4800                  0               0              0              0   
4801                  0               0              0              0   
4802                  0               0              0              0   

      western history  western music  western romance  western thriller  
0                   0              0                0                 0  
1                   0              0                0                 0  
2                   0              0                0                 0  
3                   0              0                0                 0  
4                   0              0                0                 0  
...               ...            ...              ...               ...  
4798                0              0                

### 장르 영화별 코사인 유사도 구하기

In [74]:
from sklearn.metrics.pairwise import cosine_similarity

genre_sim = cosine_similarity(genre_mat, genre_mat)
print(genre_sim.shape)
print(genre_sim[:5])

# 숫자가 높을 수록 유사도가 높다

(4803, 4803)
[[1.         0.59628479 0.4472136  ... 0.         0.         0.        ]
 [0.59628479 1.         0.4        ... 0.         0.         0.        ]
 [0.4472136  0.4        1.         ... 0.         0.         0.        ]
 [0.12598816 0.16903085 0.3380617  ... 0.12598816 0.         0.        ]
 [0.75592895 0.3380617  0.50709255 ... 0.         0.         0.        ]]


In [75]:
# test : argsort()

import numpy as np

a = np.array([1.5, 0.2 , 4.2, 2.5])
s = a.argsort() 

print(s) # 낮은 순에서 큰 순으로 솔팅해준 
print(a[s])
print(a[s[::-1]]) # 인덱스 어레이를 뒤집어서 정렬에 사용
print(a[s][::-1]) # 오름차순으로 정렬된 데이터를 뒤집어서 정렬

[1 0 3 2]
[0.2 1.5 2.5 4.2]
[4.2 2.5 1.5 0.2]
[4.2 2.5 1.5 0.2]


In [76]:
genre_sim

array([[1.        , 0.59628479, 0.4472136 , ..., 0.        , 0.        ,
        0.        ],
       [0.59628479, 1.        , 0.4       , ..., 0.        , 0.        ,
        0.        ],
       [0.4472136 , 0.4       , 1.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 1.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        1.        ]])

In [77]:
genre_sim_sorted_ind = genre_sim.argsort()[:, ::-1]
print(genre_sim_sorted_ind[:1])

[[   0 3494  813 ... 3038 3037 2401]]


In [78]:
a = np.array([[7, 5, 4, 8],[1.5, 0.2, 4.2, 2.5]])
a

array([[7. , 5. , 4. , 8. ],
       [1.5, 0.2, 4.2, 2.5]])

In [79]:
type(genre_sim_sorted_ind)

numpy.ndarray

## 특정 영화와 장르별 유사도가 높은 영화를 반환

In [85]:
def find_sim_movie(df, sorted_ind, title_name, top_n=10):
    # title_name의 정보를 추출
    title_movie = df[df['title'] == title_name]
    # title_named을 가진 DataFrame의 index 객체를 ndarray로 반환하고
    title_index = title_movie.index.values
    # sorted_ind 인자로 입력된 genre_sim_sorted_ind 객체에서 유사도 순으로 top_n 개의 index 추출
    similar_indexes = sorted_ind[title_index, :(top_n)] # sorted_ind 유사도
    similar_indexes = similar_indexes.reshape(-1)
    
    return df.iloc[similar_indexes]

In [86]:
similar_movies = find_sim_movie(movies_df, genre_sim_sorted_ind, 'The Godfather',10)
similar_movies[['title', 'vote_average']]

title  vote_average
2731                          The Godfather: Part II           8.3
1243                                    Mean Streets           7.2
3636                                   Light Sleeper           5.7
1946  The Bad Lieutenant: Port of Call - New Orleans           6.0
2640         Things to Do in Denver When You're Dead           6.7
4065                                      Mi America           0.0
1847                                      GoodFellas           8.2
4217                                            Kids           6.8
883                              Catch Me If You Can           7.7
3866                                     City of God           8.1

#### 장르유사도 + 평점 데이터를 적용한 분석

In [ ]:
# [유의사항] 
# 평점이 10인데 투표는 1건
# The Godfatehr/shawssank redemption 투표수가 많음(신뢰할만한 평점데이터)
movies_df[['title','vote_average','vote_count']].sort_values('vote_average', ascending=False)[:10]

#### weighted rating : 평점 투표 횟수(vote_count)를 반영
* 평가 횟수에 대한 가중치가 부여된 평점(Weighted Rating) 계산
* 가중 평점(Wegithed Rating) = (v/(v+m)) R + (m/(v+m)) C

In [89]:
# v : 개별 영화에 평점을 투표한 횟수
# m : 평점을 부여하기 위한 최소 투표 횟수
# R : 개별 영화에 대한 평균 평점.
# C : 전체 영화에 대한 평균 평점.

C = movies_df['vote_average'].mean()
m = movies_df['vote_count'].quantile(0.6) # 370회
print('C:', round(C,3), 'm:', round(m,3))

C: 6.092 m: 370.2


#### 가중평균 구하는 함수

In [94]:
percentile = 0.6
m = movies_df['vote_count'].quantile(percentile)
C = movies_df['vote_average'].mean()

def weighted_vote_average(record):
    v = record['vote_count']
    R = record['vote_average']
    
    return ( (v/(v+m)) * R ) + ( (m/(m+v)) * C)

In [95]:
movies_df['weighted_vote'] = movies_df.apply(weighted_vote_average,axis=1)

In [97]:
movies_df[['title','vote_average', 'weighted_vote', 'vote_count']].sort_values('weighted_vote',
                                                                              ascending=False)[:10]

title  vote_average  weighted_vote  vote_count
1881  The Shawshank Redemption           8.5       8.396052        8205
3337             The Godfather           8.4       8.263591        5893
662                 Fight Club           8.3       8.216455        9413
3232              Pulp Fiction           8.3       8.207102        8428
65             The Dark Knight           8.2       8.136930       12002
1818          Schindler's List           8.3       8.126069        4329
3865                  Whiplash           8.3       8.123248        4254
809               Forrest Gump           8.2       8.105954        7927
2294             Spirited Away           8.3       8.105867        3840
2731    The Godfather: Part II           8.3       8.079586        3338

In [98]:
def find_sim_movie(df, sorted_ind, title_name, top_n=10):
    title_movie = df[df['title'] == title_name]
    title_index = title_movie.index.values
    
    # top_n의 2배에 해당하는 쟝르 유사성이 높은 index 추출
    similar_indexes = sorted_ind[title_index, :(top_n*2)]
    similar_indexes = similar_indexes.reshape(-1)
    
# 기준 영화 index는 제외
    similar_indexes = similar_indexes[similar_indexes != title_index]
    
    # top_n의 2배에 해당하는 후보군에서 weighted_vote 높은 순으로 top_n 만큼 추출
    return df.iloc[similar_indexes].sort_values('weighted_vote', ascending=False)[:top_n]
similar_movies = find_sim_movie(movies_df, genre_sim_sorted_ind, 'The Godfather',10)
similar_movies[['title', 'vote_average', 'weighted_vote']]

title  vote_average  weighted_vote
2731       The Godfather: Part II           8.3       8.079586
1847                   GoodFellas           8.2       7.976937
3866                  City of God           8.1       7.759693
1663  Once Upon a Time in America           8.2       7.657811
883           Catch Me If You Can           7.7       7.557097
281             American Gangster           7.4       7.141396
4041              This Is England           7.4       6.739664
1149              American Hustle           6.8       6.717525
1243                 Mean Streets           7.2       6.626569
2839                     Rounders           6.9       6.530427