## Numpy ndarray 개요

In [2]:
import numpy as np

### 리스트, 튜플 차이점
1. 값을 변화할 수 있는가 여부
2.  t2 = (1,)처럼 단지 1개의 요소만을 가질 때는 요소 뒤에 콤마(,)를 반드시 붙여야 한다
* array() 안에 하나의 리스트만 들어가므로 리스트의 리스트를 넣어야 한다.

In [14]:
# ndarray 는 N-dimensional Array의 약자

array1 = np.array([1,2,3])
print('array1 type:', type(array1))

# 1차원 array로 3개 데이터, 명확하게 1차원 표현 (3,)
# 1차원의 경우에는 (열,행): 1차원은 튜플이 하나만 있는거와 같기때문이다.
print('array1 array 형태:',array1.shape) 

array2 = np.array([[1,2,3],
                  [2,3,4]])
print('array2 type:',type(array2))
print('array2 array 형태:' , array2.shape)

array3 = np.array([[1,2,3]])
print('array3 type:', type(array3))

# 2차원 array 6개 데이터, 명확하게 2차원 표현 (1,3)
print('array3 array 형태:' ,array3.shape)

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [15]:
print('array1: {:0}차원, array2: {:1}차원, array3: {:2}차원'.format(array1.ndim, array2.ndim, array3.ndim))

array1: 1차원, array2: 2차원, array3:  2차원


In [16]:
# ndarray 데이터값 숫자, 문자열, 불 값 등 모두 가능, 같은 데이터 타입만 가능
list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype) # dtype 속성 확인

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


In [17]:
# 만약 다른 데이터 유형 섞여 있는 리스트 ndarray로 변경하면 
# 데이터 크기가 더 큰 데이터 타입으로 형 변환 일괄적용

list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U11
[1. 2. 3.] float64


In [21]:
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1=array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2=array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


### arange : 파이썬 표준 함수 range()와 유사한 기능
* array를 range()로 표현

In [22]:
sequence_array = np.arange(10) # 0부터 함수 인자값 -1까지 값을 순차로 ndarray 데이터값으로 변환
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


### ndarray를 편리하게 생성하기 - arange, zeros, ones
* zeros() : 튜플 형태 shape 값 입력하면 모든 값을 0으로 채운 해당 shape ndarray 반환
* ones() : 튜플 형태 shape 값 입력하면 모든 값 1로 채운 shape ndarray 반환


In [7]:
zero_array = np.zeros((3,2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


### ndarray 차원과 크기를 변경하는 reshape()
* reshpe : 지정한 사이즈로 변경 불가능하며 오류 발생

In [17]:
array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2,5)
print('array2:\n', array2)

array3 = array1.reshape(5, 2)
print('array3:\n', array3)


array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [18]:
array1.reshape(4,3)

ValueError: cannot reshape array of size 10 into shape (4,3)

In [20]:
array1 = np.arange(10)
print(array1)
array2 = array1.reshape(-1, 5)  # 로우 인자가 -1, 칼럼 인자가 5, 2 X 5
print('array2 shape:', array2.shape)
array3 = array1.reshape(5, -1)  # 5 X 2
print('array3 shpae:', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shpae: (5, 2)


In [7]:
array1 = np.arange(8)
array3d = array1.reshape((2, 2, 2))
print('array3d:\n', array3d.tolist())  # tolist 이용해 리스트 자료형으로 변환

# 3차원 ndarray 2차원 ndarray 변환
array5 = array3d.reshape(-1, 1)
print('array5:\n', array5.tolist())
print('array6 shpae:', array5.shape)

# 1차원 ndarray 2차원 ndarray 변환

array6 = array1.reshape(-1, 1)
print('array6: \n', array6.tolist())
print('array6 shpae:', array6.shape)


array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shpae: (8, 1)
array6: 
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shpae: (8, 1)
